version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste

  